# Phase 5.A capabilities/ — 由 Plan 03 独占写完整 exports（避免与 Plan 02 并行写冲突）。
# 本 Plan 02 仅创建空文件让 Python import resolution 工作，子模块直接导入：
#   from app.agent_builder.platforms.capabilities.im import IMCapability, ...
#   from app.agent_builder.platforms.capabilities.doc import DocCapability, ...
# Plan 03 Task 2 将在此文件写完整的 6 capability re-export。
